spring.application.name=spring-basics

spring.datasource.url=jdbc:mysql://localhost:3306/oms
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=Welcome@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


com.tek.cors.url=com.tek.cors.url=http://localhost:3000
com.tek.security.jwt.jwtSecret=4p7Q9vS2zW5x8y/B?E(G+KbPeShVmYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G
com.tek.security.jwt.jwtExpirationMs=100000000